{{- if .Values.ingress.hostName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "beacon.fullname" . }}-ingress
  labels:
    app: {{ template "beacon.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
    {{- if .Values.ingress.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ template "beacon.fullname" . }}
            port:
              number:  {{ .Values.service.port }}
  {{- if .Values.ingress.useTLS }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ if .Values.ingress.secretName }}{{ .Values.ingress.secretName }}{{- else }}"{{ template "beacon.fullname" . }}-ingress-cert"{{- end }}
  {{- end }}
{{- end }}
