{{- if not (or .Values.postgresql.enabled .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "beacon.fullname" . }}
data:
  postgresql-password: {{ required "A .Values.externalDatabase.password is required" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
