apiVersion: v1
kind: Secret
metadata:
  name: {{ template "beacon.fullname" . }}
data:
  databasePasswd: {{ required "A .Values.externalDatabase.password is required" .Values.externalDatabase.password | b64enc | quote }}
